import "./globals.css";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { calFont, interFont, poppinsFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-inter antialiased",
          calFont.variable,
          interFont.variable,
          poppinsFont.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
